import {request as httpsRequest} from 'node:https';
import {Buffer} from 'node:buffer';
import {integrationSecrets} from './integration-secrets.mjs';
export const ORIGINS={imperatriz:'https://imp.ogrupors.com.br',araguaina:'https://arg.ogrupors.com.br',acailandia:'https://acl.ogrupors.com.br',maraba:'https://mab.ogrupors.com.br'};
const err=(message,status=502)=>Object.assign(Error(message),{status});
export function value(row,keys){for(const k of keys){const key=Object.keys(row||{}).find(x=>x.toLowerCase()===k.toLowerCase());const v=row?.[key];if(v!==null&&v!==undefined&&typeof v!=='object'&&String(v).trim())return String(v).trim();}return '';}
export function rows(data){if(Array.isArray(data))return data.filter(x=>x&&typeof x==='object');if(!data||typeof data!=='object')return [];for(const k of ['data','dados','veiculos','vehicles','equipamentos','equipment','localizacao','localizacoes','locations','items','rows','results','records','content','result','inventary','sims']){if(data[k]!==undefined){const found=rows(data[k]);if(found.length)return found;}}return Object.keys(data).some(k=>/^(placa|plate|serial|imei|iccid|numeroEquipamento)$/i.test(k))?[data]:[];}
export function serialOf(row){for(const source of [row,row?.equipamento,row?.equipment,row?.tracker])for(const k of ['serial','numero_serie','numeroSerie','numeroSerieEquipamento','serialEquipamento','imei','numeroEquipamento','numero_equipamento','equipment_number']){const v=value(source,[k]);if(/^\d{6,17}$/.test(v))return v;}return '';}
function tokenOf(data){if(!data||typeof data!=='object')return '';const t=value(data,['token','access_token','accessToken','jwt','id_token']);if(t)return t;for(const v of Object.values(data)){const nested=tokenOf(v);if(nested)return nested;}return '';}
export function plain(html){return String(html).replace(/<[^>]*>/g,'').replace(/&#(\d+);/g,(_,n)=>String.fromCodePoint(+n)).replace(/&(amp|nbsp|lt|gt|quot|apos|atilde|ccedil|iacute);/g,(_,n)=>({amp:'&',nbsp:' ',lt:'<',gt:'>',quot:'"',apos:"'",atilde:'ã',ccedil:'ç',iacute:'í'}[n])).trim();}
export function table(html){const body=html.match(/<tbody[^>]*>([\s\S]*?)<\/tbody>/i)?.[1];if(body===undefined||/<form[^>]*action=["'][^"']*login\.php/i.test(html))throw err('Portal não confirmou a sessão ou o formato da resposta.');return [...body.matchAll(/<tr[^>]*>([\s\S]*?)<\/tr>/gi)].map(m=>({html:m[1],cells:[...m[1].matchAll(/<td[^>]*>([\s\S]*?)<\/td>/gi)].map(c=>plain(c[1]))}));}
export function normalize(raw){const row={...raw};for(const k of ['localizacao','location','posicao','position','ultimaPosicao','lastPosition','telemetria','telemetry','dados','coordinates'])if(raw?.[k]&&typeof raw[k]==='object'&&!Array.isArray(raw[k]))for(const [name,v] of Object.entries(raw[k]))if(row[name]===undefined)row[name]=v;return {serial:serialOf(row),plate:value(row,['placa','plate','placaVeiculo']),client:value(row,['cliente','client','nomeClienteTitular']),vehicle_id:value(row,['veiculo_id','vehicle_id','veiculoId','vehicleId','codVeiculo','idVeiculo','id_veiculo','id']),phone:value(row,['telefone','numeroTelefone','phone']),iccid:value(row,['iccid','numeroChip','chip']),apn:value(row,['apn']),lat:value(row,['latitude','lat']),lng:value(row,['longitude','lng','lon']),speed:value(row,['velocidade','speed']),ignition:value(row,['ignicao','ignition','StatusIgnicao','status_ignicao']),battery:value(row,['bateria','battery','voltage']),updated_at:value(row,['ultima_comunicacao','dataServidor','DataServidor','DataComunicacao','data_comunicacao','updated_at']),gps_at:value(row,['dataGPS','gps_at','dataEvento'])};}
// The upstream PHP endpoint looks up Authorization case-sensitively.
// HTTP/1 preserves its spelling; Fetch on the hosted runtime lowercases it.
function exactCaseRequest(url,{method,headers,body}){
 if(globalThis.Deno?.connectTls)return tlsRequest(url,{method,headers,body});
 return new Promise((resolve,reject)=>{
  const req=httpsRequest(url,{method,headers,agent:false},res=>{
   const responseHeaders=new Headers();for(const [key,v] of Object.entries(res.headers))if(v!==undefined)responseHeaders.set(key,Array.isArray(v)?v.join(', '):v);
   resolve({ok:res.statusCode>=200&&res.statusCode<300,status:res.statusCode,headers:responseHeaders,body:res});
  });req.setTimeout(18000,()=>req.destroy(Error('Timeout')));req.on('error',reject);if(body)req.write(body);req.end();
 });
}
export async function tlsRequest(url,{method,headers,body}){
 const target=new URL(url);let connection,expired=false,rejectTimeout;
 const timeout=new Promise((_,reject)=>{rejectTimeout=reject;});
 const deadline=setTimeout(()=>{expired=true;try{connection?.close();}catch{}rejectTimeout(Error('Timeout'));},18000);
 try{
  connection=await Promise.race([Deno.connectTls({hostname:target.hostname,port:443}).then(c=>{if(expired){c.close();throw Error('Timeout');}return c;}),timeout]);
  const payload=body?Buffer.from(body):Buffer.alloc(0),request=Buffer.concat([Buffer.from(method+' '+target.pathname+target.search+' HTTP/1.1\r\nHost: '+target.hostname+'\r\nConnection: close\r\nAccept-Encoding: identity\r\n'+Object.entries(headers).map(([k,v])=>k+': '+v+'\r\n').join('')+(payload.length?'Content-Length: '+payload.length+'\r\n':'')+'\r\n'),payload]);
  let sent=0;while(sent<request.length)sent+=await connection.write(request.subarray(sent));
  const chunks=[];let size=0;while(true){const chunk=new Uint8Array(16384),n=await connection.read(chunk);if(n===null)break;size+=n;if(size>8*1024*1024)throw Error('Response limit');chunks.push(Buffer.from(chunk.subarray(0,n)));}
  const bytes=Buffer.concat(chunks),end=bytes.indexOf('\r\n\r\n');if(end<0)throw Error('Invalid HTTP response');const lines=bytes.subarray(0,end).toString().split('\r\n'),status=Number(lines.shift().split(' ')[1]),responseHeaders=new Headers();for(const line of lines){const at=line.indexOf(':');if(at>0)responseHeaders.append(line.slice(0,at),line.slice(at+1).trim());}
  let data=bytes.subarray(end+4);
  if(/chunked/i.test(responseHeaders.get('transfer-encoding')||'')){const decoded=[];let at=0;while(true){const next=data.indexOf('\r\n',at);if(next<0)throw Error('Invalid chunk');const length=parseInt(data.subarray(at,next).toString().split(';')[0],16);if(!Number.isFinite(length)||length<0)throw Error('Invalid chunk size');if(!length)break;at=next+2;if(at+length+2>data.length)throw Error('Incomplete chunk');decoded.push(data.subarray(at,at+length));at+=length+2;}data=Buffer.concat(decoded);}
  return{ok:status>=200&&status<300,status,headers:responseHeaders,body:[data]};
 }finally{clearTimeout(deadline);try{connection?.close();}catch{}}
}
async function transport(url,{method='GET',headers={},body,allowRedirect=false}={}){
 let r;try{r=headers.Authorization&&Object.values(ORIGINS).includes(new URL(url).origin)?await exactCaseRequest(url,{method,headers,body}):await fetch(url,{method,headers,body,redirect:'manual',signal:AbortSignal.timeout(18000)});}catch{throw err('Integração indisponível ou tempo de consulta excedido.');}
 if(!r.ok&&!(allowRedirect&&[302,303].includes(r.status)))throw Object.assign(err('Integração retornou HTTP '+r.status,r.status===401||r.status===403?502:503),{upstreamStatus:r.status});
 const chunks=[];let size=0;for await(const chunk of r.body){size+=chunk.length;if(size>8*1024*1024)throw err('Resposta excedeu o limite seguro. Reduza o período.');chunks.push(chunk);}
 const bytes=Buffer.concat(chunks);let text=new TextDecoder('utf-8').decode(bytes);if(text.includes('\ufffd'))text=new TextDecoder('windows-1252').decode(bytes);
 return {text,headers:r.headers,status:r.status};
}
function json(text){let data;try{data=JSON.parse(text);}catch{throw err('Integração retornou um formato inválido.');}if(data?.ok===false||data?.success===false||data?.status===false||data?.error||data?.erro)throw err('Integração recusou a consulta.');return data;}
async function authenticate(fn){try{return await fn();}catch(e){if([401,403].includes(e.upstreamStatus)||/não confirmou autenticação|recusou a consulta|não confirmou autenticação/.test(e.message))e.credentialInvalid=true;throw e;}}
export function connectionState(v){const text=String(v??'').trim().toLowerCase();if(['1','true','online','connected','conectado','on'].includes(text))return 'Online';if(['0','false','offline','disconnected','desconectado','off'].includes(text))return 'Off';return 'Não informado';}
export class Integrations{
 constructor({secrets=integrationSecrets,request=transport}={}){this.secrets=secrets;this.request=request;this.sessions=new Map();this.health=new Map();}
 credentials(branch,api=false){const s=this.secrets(),prefix=branch==='imperatriz'?'grupo_rs_modern':'grupo_rs_legacy_'+branch;const username=(api&&branch==='imperatriz'?s.grupo_rs_api_user:'')||s[prefix+'_user']||s.grupo_rs_legacy_user||s.grupo_rs_modern_user;const password=(api&&branch==='imperatriz'?s.grupo_rs_api_password:'')||s[prefix+'_password']||s.grupo_rs_legacy_password||s.grupo_rs_modern_password;if(!username||!password)throw err('Acesso desta base não configurado.');return{username,password};}
 async session(branch){if(!ORIGINS[branch])throw err('Base inválida.',400);let s=this.sessions.get(branch);if(s&&Date.now()-s.at<15*60*1000)return s;s={at:Date.now(),cookies:new Map(),token:''};this.sessions.set(branch,s);return s;}
 async api(branch,path,retry=true){const s=await this.session(branch);if(!s.token){if(!s.login)s.login=authenticate(async()=>{const c=this.credentials(branch,true),r=await this.request(ORIGINS[branch]+'/api_rest_app/endpoints/v1/auth/login.php',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({usuario:c.username,senha:c.password})});s.token=tokenOf(json(r.text));if(!s.token)throw err('API não confirmou autenticação.');}).catch(e=>{e.message='Autenticação da API: '+e.message;throw e;}).finally(()=>{s.login=null;});await s.login;}
 try{const r=await this.request(ORIGINS[branch]+'/api_rest_app'+path,{headers:{Authorization:'Bearer '+s.token,Accept:'application/json'}});return json(r.text);}catch(e){if(retry&&e.upstreamStatus===401){s.token='';return this.api(branch,path,false);}e.message='Consulta autenticada da API: '+e.message;throw e;}}
 async portalRequest(branch,path,fields){const s=await this.session(branch);const r=await this.request(ORIGINS[branch]+path,{method:fields?'POST':'GET',allowRedirect:!!fields,headers:{Cookie:[...s.cookies].map(([k,v])=>k+'='+v).join('; '),...(fields?{'Content-Type':'application/x-www-form-urlencoded'}:{})},body:fields?new URLSearchParams(fields).toString():undefined});for(const v of r.headers.getSetCookie()){const pair=v.split(';')[0],at=pair.indexOf('=');if(at>0)s.cookies.set(pair.slice(0,at),pair.slice(at+1));}return r.text;}
 async portal(branch,path,retry=true){const s=await this.session(branch);if(!s.portalReady){if(!s.portalLogin)s.portalLogin=(async()=>{const c=this.credentials(branch);await this.portalRequest(branch,'/login.php');await this.portalRequest(branch,'/login.php',{usuario:c.username,senha:c.password});s.portalReady=true;})().finally(()=>{s.portalLogin=null;});await s.portalLogin;}const html=await this.portalRequest(branch,path);if(/<form[^>]*action=["'][^"']*login\.php/i.test(html)){s.portalReady=false;if(retry)return this.portal(branch,path,false);throw Object.assign(err('Credencial do portal rejeitada.'),{credentialInvalid:true});}return html;}
 async vehicles(branch,serial){if(!/^\d{6,17}$/.test(serial))throw err('Informe a série numérica exata.',400);const data=await this.api(branch,'/endpoints/veiculos.php?q='+encodeURIComponent(serial)+'&skip=0&take=50');const found=rows(data);if(found.length>=50)throw err('Consulta ampla; vínculo único não confirmado.');return found.filter(r=>serialOf(r)===serial).map(normalize);}
 async binding(branch,serial){const found=await this.vehicles(branch,serial);if(found.length!==1)return{ok:false,category:'review',message:found.length?'Mais de um vínculo exato.':'Nenhum vínculo exato retornado.',serial};const row=found[0];const html=await this.portal(branch,'/cadastro/veiculos_listar.php?busca='+encodeURIComponent(serial)+'&status=Todos');const matches=table(html).filter(r=>r.cells.length>=7&&r.cells[4]===serial&&r.cells[0].replace(/\W/g,'').toUpperCase()===row.plate.replace(/\W/g,'').toUpperCase());if(matches.length!==1||!matches[0].cells[5])return{...row,ok:false,category:'review',message:'Titular não confirmado no portal.'};row.client=matches[0].cells[5];row.vehicle_id=matches[0].html.match(/veiculos_editar\.php\?id=(\d+)/)?.[1]||row.vehicle_id;const compact=row.plate.replace(/\W/g,'').toUpperCase();const internal=/^(AAA|GRS|XRS|NOV)/.test(compact);const stock=row.client.toUpperCase()==='RS300'&&(internal||! /^[A-Z]{3}\d[A-Z\d]\d{2}$/.test(compact));const ok=!stock&&!internal&&/^[A-Z]{3}\d[A-Z\d]\d{2}$/.test(compact)&&row.client.toUpperCase()!=='RS300';return{...row,ok,category:stock?'stock':ok?'eligible':'review',message:stock?'Permanece em estoque':ok?'Vínculo confirmado':'Conferir vínculo',source:ORIGINS[branch],queried_at:new Date().toISOString()};}
 async maintenance(branch){const html=await this.portal(branch,'/get_veiculos_intervalo.php?intervalo=Manutencao');const expected=plain(html).match(/Ve[ií]culos\s*\(\s*([\d.]+)\s*\)/i);if(!expected)throw err('Total de manutenção não confirmado.');const result=table(html).filter(r=>r.cells.length>=6).map(({cells:c})=>({client:c[0],plate:c[1],serial:c[2],apn:c[3],phone:c[4],updated_at:c[5],branch}));if(result.length!==Number(expected[1].replaceAll('.','')))throw err('Lista de manutenção incompleta.');return{rows:result,count:result.length,source:ORIGINS[branch],queried_at:new Date().toISOString()};}


 async equipment(branch,serial){if(!/^\d{6,17}$/.test(serial))throw err('Série inválida.',400);const d=await this.api(branch,'/endpoints/equipamentos.php?q='+encodeURIComponent(serial)+'&skip=0&take=50');const all=rows(d);const matches=all.filter(r=>serialOf(r)===serial);if(all.length>=50||matches.length!==1)throw err('Aparelho único não confirmado na API.',422);const raw=matches[0],id=value(raw,['codEquipamento','idEquipamento','equipment_id','id']);if(!/^\d+$/.test(id)||Number(id)<=0||['I','INATIVO','INACTIVE','0'].includes(value(raw,['status','situacao']).toUpperCase()))throw err('Aparelho inativo ou sem código confirmado.',422);return{...normalize(raw),id};}
 async equipmentPortal(branch,serial){if(!/^\d{6,17}$/.test(serial||''))throw err('Série inválida.',400);const html=await this.portal(branch,'/cadastro/equipamentos_listar.php?busca='+encodeURIComponent(serial)+'&status=todos');const matches=table(html).filter(r=>r.cells.length>=6&&r.cells[0]===serial);if(matches.length!==1)throw err('Série única não confirmada no portal.');const c=matches[0].cells,modern=c.length>=7;return{serial,plate:c[modern?2:1],client:c[modern?3:2],iccid:c[modern?4:3],phone:c[modern?5:4],status:c[modern?6:5]};}
 async prepareLink(branch,serial,plate){const compact=plate.toUpperCase().replace(/[ -]/g,'');if(!/^(AAA|GRS|XRS)\d{1,6}$/.test(compact))throw err('Use identificação AAA, GRS ou XRS com um a seis dígitos.',400);plate=compact.slice(0,3)+' - '+compact.slice(3);const equipment=await this.equipment(branch,serial),portal=await this.equipmentPortal(branch,serial);const found=[];for(const q of [serial,plate,compact]){const list=rows(await this.api(branch,'/endpoints/veiculos.php?q='+encodeURIComponent(q)+'&skip=0&take=50'));if(list.length>=50)throw err('Consulta ampla.');for(const r of list.map(normalize)){if(r.serial===serial||r.plate.replace(/[ -]/g,'')===compact)if(!found.some(x=>x.vehicle_id===r.vehicle_id&&x.serial===r.serial&&x.plate===r.plate))found.push(r);}}
 const confirmed=found.length===1&&found[0].serial===serial&&found[0].plate.replace(/[ -]/g,'')===compact&&portal.plate.replace(/[ -]/g,'')===compact&&portal.client.toUpperCase()==='RS300';if(confirmed)return{confirmed:true,serial,plate};if(found.length||!['','-','—'].includes(portal.plate))throw err('Aparelho ou identificação possui vínculo diferente. Nada foi substituído.',409);const clients=(await this.clients(branch,'RS300')).filter(c=>c.name.toUpperCase()==='RS300'&&/^\d+$/.test(c.id));if(clients.length!==1)throw err('Titular RS300 não confirmado de forma única.');return{confirmed:false,serial,plate,payload:{placa:plate,codEquipamento:Number(equipment.id),codCliente:Number(clients[0].id),codTipoVeiculo:1,status:'A'}};}
 async createLink(branch,payload){const session=await this.session(branch);if(!session.token)throw err('Sessão não preparada.');const r=await this.request(ORIGINS[branch]+'/api_rest_app/endpoints/veiculos.php',{method:'POST',headers:{Authorization:'Bearer '+session.token,'Content-Type':'application/json'},body:JSON.stringify(payload)});return{accepted:r.status>=200&&r.status<300};}
 async location(branch,serial){const binding=await this.binding(branch,serial);if(!binding.vehicle_id)throw err('Vínculo do veículo não confirmado.',422);const data=await this.api(branch,'/endpoints/localizacao.php?q='+encodeURIComponent(binding.plate||serial)+'&skip=0&take=50');const all=rows(data);if(all.length>=50)throw err('Localização incompleta.');const matches=all.map(normalize).filter(r=>r.serial===serial||(!r.serial&&r.vehicle_id===binding.vehicle_id&&r.plate.replace(/\W/g,'')===binding.plate.replace(/\W/g,'')));if(matches.length!==1)return{ok:false,message:'Uma localização única não foi confirmada.'};return{ok:true,...matches[0],serial,client:binding.client,source:ORIGINS[branch],queried_at:new Date().toISOString()};}
 async stockDetails(branch,serial){
 const capture=async fn=>{try{return await fn();}catch(e){return{ok:false,message:e.message};}};
 const [equipment,location]=await Promise.all([capture(()=>this.equipmentPortal(branch,serial)),capture(()=>this.location(branch,serial))]);
 let chip={ok:false,message:'ICCID não confirmado na plataforma.'};
 if(/^89\d{17,18}$/.test(equipment.iccid||'')){
  const first=await capture(()=>this.carrier('arya',equipment.iccid));
  if(first.ok)chip=first;
  else {const second=await capture(()=>this.carrier('link',equipment.iccid));chip=second.ok?second:{ok:false,message:'Arya: '+first.message+' • Link: '+second.message};}
 }
 return{serial,equipment,location,chip,source:ORIGINS[branch],queried_at:new Date().toISOString()};
 }
 async clients(branch,q){if(!q||q.length<2||q.length>120)throw err('Informe ao menos dois caracteres.',400);const result=[];for(let page=1;page<=20;page++){const d=json(await this.portal(branch,'/get_data.php?acao=clientes_select2&q='+encodeURIComponent(q)+'&term='+encodeURIComponent(q)+'&page='+page));if(!Array.isArray(d.items))throw err('Formato de clientes não confirmado.');result.push(...d.items.map(r=>({id:String(r.id),name:String(r.text)})));if(!d.more)return result;}throw err('Busca ampla. Informe um nome mais completo.');}
 async history(branch,serial,start,end){if(![start,end].every(v=>typeof v==='string'&&/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}(?::\d{2})?$/.test(v)))throw err('Informe data e horário válidos de até sete dias.',400);const a=Date.parse(start),b=Date.parse(end);if(!Number.isFinite(a)||!Number.isFinite(b)||b<a||b-a>7*86400000)throw err('Informe um período válido de até sete dias.',400);const binding=await this.binding(branch,serial);if(!binding.client||!binding.vehicle_id)throw err('Veículo não confirmado.',422);const clients=(await this.clients(branch,binding.client)).filter(c=>c.name.toLowerCase()===binding.client.toLowerCase());if(clients.length>5)throw err('Titular ambíguo.');const matched=[];for(const c of clients){const links=json(await this.portal(branch,'/get_data.php?acao=veiculos&cliente='+encodeURIComponent(c.id)+'&mapa_rapido=1&leve=1'));if(!Array.isArray(links))throw err('Vínculos não confirmados.');if(links.some(r=>String(r.CodVeiculo||r.id)===binding.vehicle_id&&typeof r.equipamento==='string'&&r.equipamento===serial))matched.push(c);}
 if(matched.length!==1)throw err('Titular e aparelho não confirmados de forma única.');const q=new URLSearchParams({cliente:matched[0].id,veiculo:binding.vehicle_id,inicio:start.replace('T',' '),fim:end.replace('T',' ')});const data=json(await this.portal(branch,'/get_eventos.php?'+q));if(!Array.isArray(data.eventos)||data.eventos.length>20000||data.eventos.some(r=>String(r.cod_veiculo)!==binding.vehicle_id))throw err('Histórico inválido ou incompleto.');return{ok:true,rows:data.eventos.map(r=>({id:String(r.id||''),gps_at:r.data_completa||r.data||'',server_at:r.data_comunicacao||'',lat:r.lat,lng:r.lng,speed:r.velocidade,ignition:r.ignicao,battery:r.bateria,internal_battery:r.bateriaInterna,memory:String(r.memoria)==='1'})),partial:Number(data.total)>data.eventos.length,distance:data.totalPercorrido??null,context:binding,source:ORIGINS[branch]};}
 async carrier(provider,iccid,retry=true){if(!['arya','link'].includes(provider)||!/^89\d{17,18}$/.test(iccid))throw err('Operadora ou ICCID inválido.',400);const s=this.secrets();const base=provider==='arya'?'https://api-arya.hinovaconecta.com.br':'https://lsm.tnsi.com.br';const key='carrier-'+provider;let auth=this.sessions.get(key);if(!auth||Date.now()-auth.at>900000){const payload=provider==='arya'?{email:s.arya_email,password:s.arya_password}:{username:s.linksolutions_email,password:s.linksolutions_password,rememberMe:true,blockInit:false};if(!payload.password)throw err('Credenciais da operadora não configuradas.');const response=await authenticate(()=>this.request(base+(provider==='arya'?'/auth':'/api/authenticate'),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)}));auth={token:response.headers.get('authorization')?.replace(/^Bearer /,'')||await authenticate(async()=>tokenOf(json(response.text))),at:Date.now()};if(!auth.token)throw Object.assign(err('Operadora não confirmou autenticação.'),{credentialInvalid:true});this.sessions.set(key,auth);}
 let response;try{response=await this.request(base+(provider==='arya'?'/customer/inventary':'/api/sims?size=10&page=1&field=iccid&value='+encodeURIComponent(iccid)+'&order=-last_conn'),{method:provider==='arya'?'POST':'GET',headers:{Authorization:'Bearer '+auth.token,'Content-Type':'application/json'},body:provider==='arya'?JSON.stringify({per_page:10,filters:{iccid}}):undefined});}catch(e){if(retry&&e.upstreamStatus===401){this.sessions.delete(key);return this.carrier(provider,iccid,false);}throw e;}const matches=rows(json(response.text)).filter(r=>value(r,['iccid','numeroChip'])===iccid);if(matches.length!==1)return{ok:false,message:'Chip exato não confirmado.',provider};const r=matches[0];return{ok:true,provider,iccid,status:value(r,['status__name','status_name','status','situacao','state','sim_status']),connectivity:connectionState(value(r,provider==='arya'?['conn_status','inSession']:['connection_status','connectionStatus','status__name','status_name'])),phone:value(r,['msisdn','number','phone','telefone']),operator:value(r,['provider','operator__name','operator','operadora','carrier']),queried_at:new Date().toISOString()};}
}
export const integrations=new Integrations();
