import test from 'node:test';import assert from 'node:assert/strict';
import {Integrations} from '../backend/integrations.mjs';
import {guardedIntegrations} from '../backend/background-sync.mjs';
import {permitted} from '../backend/user-access.mjs';
const serial='024000001';
function fixture(){const s=new Integrations();let eq={id:'4',serial,vehicle_id:''},v={codVeiculo:7,placa:'XRS - 083',titular:{codCliente:5,nomeCliente:'RS300'},qtdClientesVinculadosAtivos:1,equipamento:null};s.equipment=async()=>eq;s.api=async()=>({veiculos:[v],paginacao:{temMais:false}});return{s,eq,v};}
test('API link prepares existing RS300 target and submits exact no-move association',async()=>{const {s}=fixture();const p=await s.prepareLink('imperatriz',serial,'xrs083');assert.equal(p.plate,'XRS - 083');assert.equal(p.confirmed,false);let calls=[];s.apiPost=async(...args)=>{calls.push(args);return {ok:true}};await s.createLink('imperatriz',p.payload);assert.deepEqual(calls,[['imperatriz','/veiculos/7/equipamento',{codEquipamento:4,mover:false}]]);});
test('API link refuses another owner, occupied target or device bound elsewhere',async()=>{for(const mode of ['owner','target','device','multiple']){const {s,eq,v}=fixture();if(mode==='owner')v.titular.nomeCliente='Another';if(mode==='target')v.equipamento={codEquipamento:9};if(mode==='device')eq.vehicle_id='99';if(mode==='multiple')v.qtdClientesVinculadosAtivos=2;await assert.rejects(s.prepareLink('imperatriz',serial,'XRS083'));}});
test('API link detects already confirmed association and sends no write',async()=>{const {s,eq,v}=fixture();eq.vehicle_id='7';v.equipamento={codEquipamento:4,numeroSerie:serial};const p=await s.prepareLink('imperatriz',serial,'XRS083');assert.equal(p.confirmed,true);s.apiPost=async()=>{throw Error('must not post')};await s.createLink('imperatriz',p.payload);});
test('API link refuses changed target after preview',async()=>{const {s,v}=fixture();const p=await s.prepareLink('imperatriz',serial,'XRS083');v.codVeiculo=8;s.apiPost=async()=>{throw Error('must not post')};await assert.rejects(s.createLink('imperatriz',p.payload),/mudou/);});
test('missing identification prepares creation without sending writes',async()=>{const {s}=fixture();s.api=async(b,path)=>path.startsWith('/associados')?{associados:[{codCliente:5,nome:'RS300',veiculos:[]}]}:{veiculos:[],paginacao:{temMais:false}};s.apiPost=async()=>{throw Error('preview must not write')};const p=await s.prepareLink('imperatriz',serial,'XRS083');assert.equal(p.create_required,true);assert.equal(p.payload.client_id,'5');});
test('API write preserves Authorization and never retries an ambiguous POST',async()=>{let calls=0;const s=new Integrations({request:async(url,options)=>{calls++;assert.equal(options.method,'POST');assert.equal(options.headers.Authorization,'Bearer synthetic');assert.deepEqual(JSON.parse(options.body),{codEquipamento:4,mover:false});throw Error('Timeout');}});(await s.session('imperatriz')).token='synthetic';await assert.rejects(s.apiPost('imperatriz','/veiculos/7/equipamento',{codEquipamento:4,mover:false}));assert.equal(calls,1);await assert.rejects(s.apiPost('imperatriz','/veiculos',{codEquipamento:4,mover:false}));assert.equal(calls,1);});
test('403 on one API route does not pause all branch reads',async()=>{let alerts=0,calls=0;const pool={query:async(sql,args)=>{if(args.length===3)alerts++;return {rows:[{blocked:false}]}}};const s=guardedIntegrations(pool,{credentials:()=>({username:'test',password:'test'}),api:async(b,path)=>{calls++;if(path==='/denied')throw Object.assign(Error('denied'),{upstreamStatus:403});return {ok:true}},carrier:async()=>{}});await assert.rejects(s.api('imperatriz','/denied'));assert.equal((await s.api('imperatriz','/veiculos')).ok,true);assert.equal(alerts,0);assert.equal(calls,2);});
test('link access allows preview and pending operations without allowing SMS writes',()=>{const a={owner:false,views:['link'],writes:['link']};assert(permitted(a,'/api/integrations/link-preview','GET'));assert(permitted(a,'/api/integrations/operations','GET'));assert(!permitted(a,'/api/integrations/sms','POST'));assert(!permitted({owner:false,views:['stock'],writes:[]},'/api/integrations/link-preview','GET'));});
import {integrationRoute} from '../backend/integration-routes.mjs';
test('pending operations are filtered by module and foreign reconciliation is denied',async()=>{
 let kinds;const client={release(){},query:async(sql,args)=>{if(sql.includes('kind=any')){kinds=args[1];return{rows:[]}}if(sql.startsWith('select kind'))return{rows:[{kind:'sms'}]};return{rows:[]}}};const pool={query:async()=>({rows:[{role:'operator'}]}),connect:async()=>client};const res={writeHead(){},end(){}};const base={res,pool,user:{user_id:'fixture'},permissions:{owner:false,views:['link'],writes:['link']},service:{},readBody:async()=>({id:'fixture'})};
 await integrationRoute({...base,req:{method:'GET'},url:new URL('http://test/api/integrations/operations?branch=imperatriz')});assert.deepEqual(kinds,['link']);
 await assert.rejects(integrationRoute({...base,req:{method:'POST'},url:new URL('http://test/api/integrations/reconcile?branch=imperatriz')}),e=>e.status===403);
});

test('creation sends exact spaced identification, confirms RS300, then associates without moving',async()=>{const {s,eq,v}=fixture();let created=false;const calls=[];s.api=async(b,path)=>path.startsWith('/associados')?{associados:[{codCliente:5,nome:'RS300',veiculos:created?[v]:[]}]}:{veiculos:created?[v]:[],paginacao:{temMais:false}};s.apiPost=async(b,path,body)=>{calls.push({path,body});if(path==='/veiculos'){created=true;return{ok:true,codCliente:5,nomeCliente:'RS300',veiculo:{CodVeiculo:7,Placa:'XRS - 083'}}}return{ok:true}};const p=await s.prepareLink('imperatriz',serial,'XRS - 083');await s.createLink('imperatriz',p.payload);assert.deepEqual(calls,[{path:'/veiculos',body:{placa:'XRS - 083',codCliente:5,codEquipamento:4,moverEquipamento:false}},{path:'/veiculos/7/equipamento',body:{codEquipamento:4,mover:false}}]);});
test('creation timeout or unconfirmed owner never sends the association',async()=>{for(const timeout of [true,false]){const {s}=fixture();s.api=async(b,path)=>path.startsWith('/associados')?{associados:[{codCliente:5,nome:'RS300',veiculos:[]}]}:{veiculos:[],paginacao:{temMais:false}};const p=await s.prepareLink('imperatriz',serial,'XRS083');let writes=0;s.apiPost=async()=>{writes++;if(timeout)throw Error('Timeout');return{codCliente:999,nomeCliente:'Another',veiculo:{CodVeiculo:7,Placa:'XRS - 083'}}};await assert.rejects(s.createLink('imperatriz',p.payload));assert.equal(writes,1);}});
test('summary target is checked against RS300 association including occupied equipment',async()=>{const {s,v}=fixture();s.api=async(b,path)=>path.startsWith('/associados')?{associados:[{codCliente:5,nome:'RS300',veiculos:[v]}]}:{veiculos:[{CodVeiculo:7,Placa:'XRS - 083'}],paginacao:{temMais:false}};assert.equal((await s.prepareLink('imperatriz',serial,'XRS083')).payload.client_id,'5');v.equipamento={codEquipamento:99,numeroSerie:'024999999'};await assert.rejects(s.prepareLink('imperatriz',serial,'XRS083'),/outro aparelho/);});
