import test from 'node:test';import assert from 'node:assert/strict';import {codeResult,scanConfig,codeTick} from '../backend/code-scan.mjs';
const row={id:'x',serial:'024364668',plate:'SMR - 4J81'},valid={ok:true,id:'4',serial:row.serial,vehicle_id:'7',plate:'SMR4J81',binding_known:true};
test('codes require exact serial and explicit unlinked evidence; compare normalized plates',()=>{assert.equal(codeResult(row,valid).state,'confirmed');assert.equal(codeResult(row,{...valid,plate:'ABC1D23'}).state,'divergent');assert.equal(codeResult(row,{...valid,vehicle_id:'',plate:''}).state,'unlinked');for(const result of [{...valid,serial:'wrong'},{...valid,id:''},{...valid,vehicle_id:'',plate:'',binding_known:false},{...valid,plate:''}])assert.throws(()=>codeResult(row,result));});
test('interval is bounded and boolean required',()=>{assert.equal(scanConfig({enabled:true,interval_seconds:25}).interval_seconds,25);for(const b of [{enabled:true,interval_seconds:24},{enabled:'true',interval_seconds:25},{enabled:true,interval_seconds:25.5}])assert.throws(()=>scanConfig(b));});
test('schedule rejects invalid windows and oversized batches; keeps legacy pause compatible',()=>{
 const input={enabled:true,interval_seconds:25,nightly_enabled:true,night_start:'22:00',night_end:'04:00',batch_limit:10,priority:true};
 assert.deepEqual(scanConfig(input),input);
 for(const change of [{night_end:'22:00'},{night_start:'25:00'},{night_start:'2:00'},{batch_limit:50},{batch_limit:0},{batch_limit:2.5},{priority:'true'},{nightly_enabled:null}])assert.throws(()=>scanConfig({...input,...change}));
 assert.deepEqual(scanConfig({enabled:false,interval_seconds:40}),{enabled:false,interval_seconds:40});
});
function fixture(){const saved=[],queries=[];const pool={query:async(sql,args)=>{queries.push(sql);if(sql.includes('code_scan_claim'))return{rows:[{data:{batch:1,rows:Array.from({length:10},(_,i)=>({...row,id:String(i)}))}}]};if(sql.includes('code_scan_save'))saved.push(args);return{rows:[]};}};return{pool,saved,queries};}
test('one batch processes ten sequentially and releases its lease',async()=>{const f=fixture();let inFlight=0,max=0;const r=await codeTick(f.pool,{service:{equipment:async()=>{max=Math.max(max,++inFlight);await Promise.resolve();inFlight--;return valid;}}});assert.equal(r.processed,10);assert.equal(max,1);assert.equal(f.saved.length,10);assert.match(f.queries.at(-1),/code_scan_release/);});
test('throttling saves pending failure and defers remaining items',async()=>{const f=fixture();const r=await codeTick(f.pool,{service:{equipment:async()=>{throw Object.assign(Error('HTTP 429'),{status:429});}}});assert.equal(r.processed,1);assert.equal(r.backoff,120);assert.equal(f.saved[0][3].state,'error');});
test('expired budget leaves unsaved items eligible for next batch',async()=>{const f=fixture();let time=0;const r=await codeTick(f.pool,{now:()=>time,budgetMs:45,service:{equipment:async()=>{time+=30;return valid;}}});assert.equal(r.processed,2);});
