import test from 'node:test';import assert from 'node:assert/strict';
import {sealToken,openToken,validateDeploymentToken,saveCentralToken} from '../backend/deployment-credential.mjs';
import {api} from '../backend/api.mjs';import {hash,passwordHash} from '../backend/auth.mjs';
test('tokens encrypted with authenticated project-bound key',async()=>{const secret='x'.repeat(32),token='sbp_'+'a'.repeat(40),sealed=await sealToken(token,secret,'one');assert.ok(!sealed.includes(token));assert.equal(await openToken(sealed,secret,'one'),token);await assert.rejects(openToken(sealed,secret,'two'));await assert.rejects(openToken(sealed,'z'.repeat(32),'one'));});
test('invalid, expired and wrong-project tokens never accepted',async()=>{await assert.rejects(validateDeploymentToken('bad','p'),{status:400});for(const status of [401,403,500])await assert.rejects(validateDeploymentToken('sbp_'+'a'.repeat(40),'p',async()=>new Response('',{status})));let n=0;await validateDeploymentToken('sbp_'+'a'.repeat(40),'p',async(url)=>{assert.ok(url.startsWith('https://api.supabase.com/v1/projects/p/'));n++;return new Response('[]');});assert.equal(n,2);});
test('failed validation leaves old stored credential untouched',async()=>{let writes=0;await assert.rejects(saveCentralToken({query:async()=>{writes++;}},'invalid','secret'));assert.equal(writes,0);});
test('Central requires owner, CSRF and password; metadata never exposes token',async()=>{const sid='a'.repeat(64),csrf=hash(sid+':csrf');async function call({owner=true,cookie=true,origin='https://central.test',method='POST',csrfHeader=csrf,password='wrong'}={}){
const pool={query:async sql=>sql.includes('from central_homologacao.sessions')?{rows:cookie?[{user_id:'owner-id',username:owner?'lucasabm':'reader',csrf_hash:hash(csrf)}]:[]} :sql.includes('memberships')?{rowCount:1,rows:[{}]}:sql.includes('password_hash')?{rows:[{password_hash:passwordHash('correct-pass')}]}:sql.includes('returning attempts')?{rows:[{attempts:1}]}:sql.includes('select updated_at')?{rows:[{updated_at:'2026-10-03'}]}:{rows:[],rowCount:0}};
const req={url:'/api/deployment-token',method,headers:{host:'central.test',origin,cookie:cookie?'central_session='+sid:'','x-csrf-token':csrfHeader},socket:{remoteAddress:'test'},async *[Symbol.asyncIterator](){yield JSON.stringify({token:'not-real',password});}};let status,body;await api(pool)(req,{setHeader(){},writeHead(s){status=s;},end(b){body=JSON.parse(b);}});return{status,body};}
assert.equal((await call({cookie:false})).status,401);assert.equal((await call({owner:false})).status,403);assert.equal((await call({origin:'https://evil.test'})).status,403);assert.equal((await call({csrfHeader:'wrong'})).status,403);assert.equal((await call()).status,403);const r=await call({method:'GET'});assert.equal(r.status,200);assert.deepEqual(Object.keys(r.body).sort(),['configured','updatedAt']);});
