import test from 'node:test';import assert from 'node:assert/strict';
import {Integrations} from '../backend/integrations.mjs';import {sourceIntegrations} from '../backend/read-sources.mjs';import {PortalRead} from '../backend/portal-read.mjs';
const serial='024000001',equipment={ok:true,id:'8',serial,vehicle_id:'7',plate:'ABC - 1D23',binding_known:true},owner={serial,vehicle_id:'7',plate:'ABC1D23',client:'Synthetic'};
function fixture({code='8',e=equipment,owners=[owner]}={}){const calls=[];const api={savedEquipmentCode:async()=>code,equipmentByCode:async(b,s,id)=>{calls.push(['code',id]);assert.equal(s,serial);return e;},equipment:async()=>{calls.push(['serial']);return e;}};const web={vehiclesByPlate:async(b,p)=>{calls.push(['web',p]);return owners;}};return{s:sourceIntegrations(api,async()=>{throw Error('not the legacy flow');},web),calls};}
test('saved equipment code obtains current plate then owner by that plate; every call is fresh',async()=>{const f=fixture();const result=await f.s.dischargeBinding('imperatriz',serial,'Old owner');assert.equal(result.client,'Synthetic');assert.equal(result.category,'eligible');assert.deepEqual(f.calls,[['code','8'],['web',equipment.plate]]);await f.s.dischargeBinding('imperatriz',serial,'Old owner',{fresh:true});assert.equal(f.calls.length,4);});
test('missing saved code resolves the serial once before web lookup',async()=>{const f=fixture({code:null});await f.s.dischargeBinding('imperatriz',serial);assert.deepEqual(f.calls,[['serial'],['web',equipment.plate]]);});
test('wrong web series, vehicle, plate, absent or duplicate rows cannot authorize discharge',async()=>{for(const owners of [[],[owner,owner],[{...owner,serial:'024000002'}],[{...owner,vehicle_id:'9'}],[{...owner,plate:'XYZ1D23'}]]){const f=fixture({owners});await assert.rejects(f.s.dischargeBinding('imperatriz',serial));}});
test('missing owner and unlinked equipment remain review; no speculative web call when unlinked',async()=>{let f=fixture({owners:[{...owner,client:''}]});assert.equal((await f.s.dischargeBinding('imperatriz',serial)).category,'review');f=fixture({e:{...equipment,vehicle_id:'',plate:''}});assert.equal((await f.s.dischargeBinding('imperatriz',serial)).category,'review');assert.deepEqual(f.calls,[['code','8']]);});
test('equipment endpoint validates exact saved code, series and active status',async()=>{for(const changed of [{codEquipamento:9},{numeroSerie:'024000002'},{ativo:false}]){const s=new Integrations();s.api=async()=>({ok:true,equipamento:{codEquipamento:8,numeroSerie:serial,ativo:true,...changed}});await assert.rejects(s.equipmentByCode('imperatriz',serial,'8'));}const s=new Integrations();s.api=async(b,path)=>{assert.equal(path,'/equipamentos/8');return{ok:true,equipamento:{codEquipamento:8,numeroSerie:serial,ativo:true,veiculo:{codVeiculo:7,placa:'ABC1D23'}}};};assert.equal((await s.equipmentByCode('imperatriz',serial,'8')).plate,'ABC1D23');});
test('web plate lookup encodes exact plate, discards different plates and rejects pagination',async()=>{const web=new PortalRead({}),html='<table id="veiculos"><thead><tr><th>PLACA</th></tr></thead><tbody><tr><td>ABC1D23</td><td>Car</td><td></td><td></td><td>'+serial+'</td><td>Synthetic</td><td>Ativo</td><td><a href="veiculos_editar.php?id=7">Editar</a></td></tr></tbody></table>';web.page=async(b,p)=>{assert.equal(new URL('https://example.test'+p).searchParams.get('busca'),'ABC - 1D23');return html;};assert.equal((await web.vehiclesByPlate('imperatriz','ABC - 1D23'))[0].client,'Synthetic');web.page=async()=>html+'Pagina 1 de 2';await assert.rejects(web.vehiclesByPlate('imperatriz','ABC1D23'),/incompleta/);});

test('analysis route uses the new code flow without the legacy binding query',async()=>{
 const {integrationRoute}=await import('../backend/integration-routes.mjs');let calls=0,output;
 await integrationRoute({pool:{query:async()=>({rows:[{role:'operator'}]})},user:{user_id:'synthetic'},req:{method:'GET',headers:{}},res:{writeHead(){},end(v){output=JSON.parse(v);}},url:new URL('https://example.test/api/integrations/binding?branch=imperatriz&serial='+serial),service:{dischargeBinding:async(b,s)=>{calls++;assert.equal(b,'imperatriz');assert.equal(s,serial);return{ok:true,category:'eligible'};},binding(){assert.fail('legacy flow');}}});assert.equal(calls,1);assert.equal(output.category,'eligible');
});
