import test from 'node:test';import assert from 'node:assert/strict';
import {Integrations,normalize,rows} from '../backend/integrations.mjs';
const secrets=()=>({grupo_rs_modern_user:'test',grupo_rs_modern_password:'test'});
const response=data=>({text:JSON.stringify(data),status:200,headers:new Headers()});
test('location singular wrapper and equipment wrapper retain official rows',()=>{assert.equal(rows({ok:true,localizacao:[{CodVeiculo:7,Placa:'ABC1D23'}]}).length,1);assert.equal(rows({equipamentos:[{numeroEquipamento:'024000001'}]}).length,1);assert.equal(normalize({CodVeiculo:7,StatusIgnicao:0,DataComunicacao:'2026-09-24 10:00:00'}).ignition,'0');});
test('communication requires exact vehicle id and does not accept another device',async()=>{const s=new Integrations();s.vehicles=async()=>[{vehicle_id:'7',plate:'ABC1D23'}];s.api=async()=>({veiculo:{codVeiculo:7},equipamento:{numeroSerie:'024000001'},comunicacao:{latitude:'-5',longitude:'-47'}});assert.equal((await s.location('imperatriz','024000001')).ok,true);await assert.rejects(s.location('imperatriz','024000002'));s.vehicles=async()=>[{vehicle_id:'8',plate:'ABC1D23'}];await assert.rejects(s.location('imperatriz','024000001'));});

test('upstream error envelope is not reported as empty result',async()=>{const s=new Integrations({secrets,request:async url=>response(url.endsWith('login')?{token:'test'}:{ok:false,error:'test'})});await assert.rejects(s.vehicles('imperatriz','024000001'),/recusou/);});
test('expired read session authenticates once and does not retry indefinitely',async()=>{let logins=0,reads=0;const s=new Integrations({secrets,request:async url=>{if(url.endsWith('login')){logins++;return response({token:'test'});}reads++;throw Object.assign(Error('expired'),{upstreamStatus:401});}});await assert.rejects(s.vehicles('imperatriz','024000001'),/expired/);assert.equal(logins,2);assert.equal(reads,2);});
