import test from 'node:test';
import assert from 'node:assert/strict';
import {lookupEquipment,inventoryCounts,exactEquipment} from '../backend/inventory-tools.mjs';
import {lowInventory} from '../public/inventory-alerts.js';
import {businessMutation} from '../backend/business.mjs';
import {Integrations} from '../backend/integrations.mjs';
import {permitted} from '../backend/user-access.mjs';
test('low stock includes zero and threshold, never missing/invalid counts',()=>{assert.equal(lowInventory(0,0),true);assert.equal(lowInventory(4,4),true);for(const x of [null,undefined,-1,'0',NaN])assert.equal(lowInventory(x,4),false);assert.equal(lowInventory(5,4),false);assert.equal(lowInventory(0,null),false);});
test('lookup preserves zeros, classifies and tolerates unavailable external data only with local match',async()=>{
 const c={query:async()=>({rows:[{id:'id',serial:'024000001',version:2,data:{identification:'XRS - 001',iccid:'8900000000000000001'}}]})};
 const result=await lookupEquipment(c,{equipmentPortal:async()=>{throw Error('Offline');}},'imperatriz','024000001');assert.equal(result.data.serial,'024000001');assert.equal(result.data.model,'V7.3.5');assert.match(result.warning,/Offline/);assert.equal(result.existing.version,2);
 await assert.rejects(lookupEquipment({query:async()=>({rows:[]})},{lookupEquipment:async()=>{throw Error('Offline');}},'imperatriz','024000001'),/Offline/);
});
test('ambiguous or mismatched remote lookup cannot fill another device',async()=>{await assert.rejects(lookupEquipment({query:async()=>({rows:[{},{}]})},{},'imperatriz','XRS001'),/Mais de um/);await assert.rejects(lookupEquipment({query:async()=>({rows:[]})},{lookupEquipment:async()=>({serial:'024000002'})},'imperatriz','024000001'),/exata/);assert.equal(exactEquipment({plate:'XRS - 001'},'xrs001'),true);});
test('counts only include authorized modules, warehouse chips separate',async()=>{const c={query:async sql=>({rows:sql.includes('warehouse_items')?[{kind:'device',n:'4'},{kind:'chip',n:'0'}]:[{n:'7'}]})};const r=await inventoryCounts(c,'imperatriz',{views:['warehouse']});assert.equal(r.stock,undefined);assert.equal(r.warehouse,4);assert.equal(r.chips,0);assert.equal(permitted({owner:false,views:['overview'],writes:[]},'/api/integrations/inventory-counts','GET'),true);assert.equal(permitted({owner:false,views:['sms'],writes:[]},'/api/integrations/inventory-counts','GET'),false);});
test('remote lookup rejects partial lists and resolves ICCID exact only',async()=>{const s=new Integrations();s.api=async()=>({equipamentos:[{numeroSerie:'024000001',numeroChip:'8900000000000000001'}],paginacao:{temMais:false}});s.equipment=async()=>({serial:'024000001',iccid:'8900000000000000001',ok:true});assert.equal((await s.lookupEquipment('imperatriz','8900000000000000001')).serial,'024000001');s.api=async()=>({equipamentos:[],paginacao:{temMais:true}});await assert.rejects(s.lookupEquipment('imperatriz','8900000000000000001'),/única/);});
const manualBody={manual:true,clientId:'',vehicleId:'',clientName:'Cliente teste',plate:'DEM1A00',currentSerial:'024000001',reason:'Sem comunicação',medium:'Consultor informou',notes:'Registro manual'};
test('manual maintenance saves with explicit provenance and without external calls in all bases',async()=>{for(const branch of ['imperatriz','araguaina','acailandia','maraba']){let saved;const c={query:async(sql,args)=>{if(sql.startsWith('insert into central_homologacao.visits'))saved=args[3];return {rows:[]};}};const service=new Proxy({},{get(){throw Error('No remote query allowed');}});const result=await businessMutation(c,{path:'/api/maintenance',method:'POST',body:manualBody,branch,user:{user_id:'qa'},role:'operator',service});assert.equal(result.response.ok,true);assert.equal(saved.identity_source,'manual');assert.equal(saved.currentSerial,'024000001');}});
test('manual maintenance validates serial and rejects unavailable replacement',async()=>{const ctx={path:'/api/maintenance',method:'POST',branch:'imperatriz',user:{user_id:'qa'},role:'operator',service:{}};const c={query:async()=>({rows:[]})};await assert.rejects(businessMutation(c,{...ctx,body:{...manualBody,currentSerial:'bad'}}),/série válidos/);await assert.rejects(businessMutation(c,{...ctx,body:{...manualBody,reason:'Troca de aparelho',replacement:'00000000-0000-0000-0000-000000000001',replacementVersion:1}}),/indisponível/);});
