import test from 'node:test';import assert from 'node:assert/strict';
import {integrationRoute} from '../backend/integration-routes.mjs';
function fixture(category,body={},role='operator'){
 const writes=[];const query=async(sql,args)=>{if(sql.includes('memberships'))return{rows:[{role}]};if(sql.startsWith('select * from central_homologacao.devices'))return{rows:[{id:'device',serial:'024000001',version:1,data:{status:'Estoque'}}]};if(sql.startsWith('update central_homologacao.devices')){writes.push(JSON.parse(args[3]));return{rowCount:1,rows:[{id:'device'}]};}if(sql.includes('insert into central_homologacao.audit_events'))writes.push(args[4]);return{rows:[],rowCount:0};};const pool={query,connect:async()=>({query,release(){}})};
 return{writes,run:()=>integrationRoute({pool,user:{user_id:'test'},req:{method:'POST',headers:{'idempotency-key':'00000000-0000-0000-0000-000000000001'}},res:{writeHead(){},end(){}},url:new URL('http://test/api/integrations/discharge?branch=maraba'),readBody:async()=>({id:'device',version:1,plate:'AAA - 001',client:'RS300',...body}),service:{binding:async()=>({ok:category==='eligible',category,plate:'AAA - 001',client:'RS300'})}})};
}
for(const category of ['stock','review'])test('explicit manual discharge for '+category,async()=>{const f=fixture(category,{manual:true,confirmedCategory:category});await f.run();assert.equal(f.writes[0].status,'Instalado');assert.equal(f.writes[1].manual,true);assert.equal(f.writes[1].category,category);});
test('automatic discharge keeps eligibility requirement',async()=>{await assert.rejects(fixture('stock').run(),e=>e.status===409);await fixture('eligible').run();});
test('manual confirmation cannot bypass failed query, changed binding or reader role',async()=>{for(const [category,body,role,status] of [['error',{manual:true,confirmedCategory:'error'},'operator',409],['review',{manual:true,confirmedCategory:'stock'},'operator',409],['stock',{manual:true,confirmedCategory:'stock',plate:'DIFFERENT'},'operator',409],['stock',{manual:true,confirmedCategory:'stock'},'reader',403]]){const f=fixture(category,body,role);await assert.rejects(f.run(),e=>e.status===status);assert.equal(f.writes.length,0);}});
