import test from 'node:test';import assert from 'node:assert/strict';
import {sourceIntegrations,mergeConfirmed,classifyBinding,saveSourceSettings} from '../backend/read-sources.mjs';
import {PortalRead,portalVehicles,formField} from '../backend/portal-read.mjs';
const row={serial:'024000001',plate:'ABC - 1234',vehicle_id:'7',client:'Cliente teste'};
for(const branch of ['imperatriz','araguaina','acailandia','maraba'])test('source isolation and owner enrichment '+branch,async()=>{
 let ac=0,wc=0;const api={vehicles:async()=>{ac++;return[{...row,client:''}]},binding:async()=>{ac++;return{category:'review'}}},web={vehicles:async()=>{wc++;return[row]}};
 const onlyWeb=sourceIntegrations(api,async()=>'web',web);assert.equal((await onlyWeb.binding(branch,row.serial)).category,'eligible');assert.equal(ac,0);
 const onlyApi=sourceIntegrations(api,async()=>'api',web);await onlyApi.binding(branch,row.serial);assert.equal(wc,1);
 const both=sourceIntegrations(api,async()=>'both',web);const got=await both.binding(branch,row.serial);assert.equal(got.client,row.client);assert.equal(got.field_sources.client,'web');
});
test('conflict and ambiguity fail closed',()=>{for(const change of [{serial:'024000002'},{plate:'XYZ - 1234'},{vehicle_id:'8'},{client:'Outro'}])assert.throws(()=>mergeConfirmed(row,{...row,...change}),/divergem/);assert.throws(()=>mergeConfirmed({...row,owner_count:'2'},row),/múltiplos/);assert.equal(classifyBinding({...row,client:'RS300',plate:'XRS - 001'},row.serial).category,'stock');});
test('zero remains data and telemetry from different samples is not mixed',()=>{const got=mergeConfirmed({...row,battery:'0',ignition:'0',gps_at:'2026-10-01T11:00',updated_at:'2026-10-01T11:00'},{...row,battery:'12',ignition:'1',lat:'-1',updated_at:'2026-10-01T12:00'});assert.equal(got.battery,'0');assert.equal(got.ignition,'0');assert.equal(got.lat,undefined);});
test('budget and bad input do not cause web fallback',async()=>{for(const status of [400,429]){const s=sourceIntegrations({equipment:async()=>{throw Object.assign(Error('fail'),{status})}},async()=>'both',{equipment:()=>assert.fail('must not call')});await assert.rejects(()=>s.equipment('imperatriz',row.serial));}});
test('invalid modes and incomplete branch configuration rejected before SQL',async()=>{await assert.rejects(()=>saveSourceSettings({query:()=>assert.fail('must not write')},{branches:[{branch_id:'imperatriz',mode:'web'}]}));});
test('API identity conflict is not hidden by web fallback',async()=>{const s=sourceIntegrations({vehicles:async()=>{throw Object.assign(Error('Vínculo divergente entre aparelho e veículo.'),{status:422})}},async()=>'both',{vehicles:()=>assert.fail('must not call')});await assert.rejects(()=>s.binding('imperatriz',row.serial),/divergente/);});
test('homonymous owners require the exact vehicle and owner code',async()=>{const p=new PortalRead({});p.vehicles=async()=>[row];p.clients=async()=>[{id:'1',name:row.client},{id:'2',name:row.client}];p.json=async(b,path)=>path.includes('get_bateria')?{veiculos:[{CodVeiculo:'7',placa:row.plate,bateria:12}]}:[{CodVeiculo:'7',placa:row.plate,equipamento:row.serial,CodClienteTitular:'2',NomeClienteTitular:row.client}];const r=await p.location('maraba',row.serial);assert.equal(r.client_id,'2');assert.equal(r.battery,'12');});
test('portal parser uses exact identity and no write endpoints',async()=>{const html='<table id="veiculos"><thead><th>PLACA</th></thead><tbody><tr><td>ABC - 1234</td><td>Moto</td><td>2026</td><td>Azul</td><td>024000001</td><td>Cliente teste</td><td>Ativo</td><td><a href="veiculos_editar.php?id=7">Editar</a></td></tr></tbody></table>';assert.deepEqual(portalVehicles(html)[0],{...row,model:'Moto',status:'Ativo'});assert.equal(formField('<select name="Apn"><option value="test" selected>Test</option></select>','Apn').value,'test');const p=new PortalRead({request:()=>assert.fail('must not call')});await assert.rejects(()=>p.request('imperatriz','/cadastro/veiculos_actions.php?acao=inativar&id=7'));});
