import test from 'node:test';import assert from 'node:assert/strict';
import {smsCloudFetch,smsCloudOperation,validSmsTransition} from '../backend/sms-cloud.mjs';
import {processSms,bridgeHealth} from '../backend/sms-queue.mjs';
const id='00000000-0000-4000-8000-000000000001',device='test-device';
test('cloud authentication fails before accessing SQL',async()=>{process.env.CENTRAL_SMS_GATEWAY_TOKEN='a'.repeat(64);const r=await smsCloudFetch(new Request('https://example.test',{method:'POST',body:'{}'}),{connect:()=>assert.fail()});assert.equal(r.status,401);});
test('cloud state never regresses and uncertain delivery is never returned to queue',()=>{assert.ok(validSmsTransition('received','delivered'));assert.ok(validSmsTransition('indeterminate','sent'));assert.equal(validSmsTransition('delivered','sent'),false);assert.equal(validSmsTransition('sent','received'),false);assert.equal(validSmsTransition('indeterminate','received'),false);});
test('diagnostic polling neither claims nor reveals payloads',async()=>{const queries=[];const r=await smsCloudOperation({query:async(sql)=>{queries.push(sql);return{rows:sql.startsWith('select id,state')?[{id,state:'pending',payload:{command:'private'}}]:[]}}},{action:'poll',ready:false},device);assert.equal(queries.some(q=>q.startsWith('with picked')),false);assert.equal(r.jobs[0].payload,undefined);});
test('cloud report is confined to claimed device and immutable terminal state',async()=>{let writes=0;const c={query:async(sql)=>{if(sql.startsWith('update'))writes++;return{rows:[{state:'delivered',result:{cloud_device:device}}]}}};await assert.rejects(smsCloudOperation(c,{action:'report',id,state:'sent'},'another'),{status:404});assert.equal((await smsCloudOperation(c,{action:'report',id,state:'sent'},device)).ignored,true);assert.equal(writes,0);});
test('PC bridge cannot send or overwrite a cloud-owned operation',async()=>{await processSms({result:{cloud_device:device}},{gateway:()=>assert.fail(),claim:()=>assert.fail(),save:()=>assert.fail()});});
test('diagnostic heartbeat is connected but cannot authorize real SMS',async()=>{const r=await bridgeHealth({query:async()=>({rows:[{healthy:true,checked_at:new Date(),details:{mode:'cloud',send_enabled:false}}]})},'imperatriz');assert.equal(r.connected,true);assert.equal(r.ok,false);assert.match(r.error,/diagnóstico/);});

test('multibase queue binds every SQL branch scope to server-authorized bases',async()=>{const branches=['imperatriz','araguaina','acailandia','maraba'],queries=[];await smsCloudOperation({query:async(sql,args)=>{queries.push([sql,args]);return{rows:[]}}},{action:'poll',ready:true},device,branches);for(const [sql,args] of queries.filter(([sql])=>/remote_operations|sms_bridge_status/.test(sql))){assert.ok(args.some(a=>Array.isArray(a)&&a.join()===branches.join()));}await assert.rejects(smsCloudOperation({query:()=>assert.fail()},{action:'poll',ready:true},device,[]),{status:403});});
